apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      containers:
        - name: sales-service
          image: sales-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/sales
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
spec:
  type: NodePort
  ports:
    - port: 5001
      nodePort: 30007
  selector:
    app: sales-service

